//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waMvcDay12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buku
    {
        public int BukuID { get; set; }
        public string Kd_Buku { get; set; }
        public string Nm_Buku { get; set; }
        public Nullable<int> Jml_Halaman { get; set; }
        public string Kd_Jenis { get; set; }
    }
}
